kubectl delete -f ./deployment/web-deployment.yaml
kubectl delete -f ./deployment/gateway-deployment.yaml
kubectl delete -f ./deployment/auth-deployment.yaml
kubectl delete -f ./deployment/system-deployment.yaml
kubectl delete -f ./deployment/ruoyi-nacos.yaml
kubectl delete -f ./deployment/ruoyi-redis.yaml
kubectl delete -f ./deployment/ruoyi-mysql.yaml
kubectl delete -f ./deployment/datakit-operator.yaml
kubectl delete -f ./deployment/datakit.yaml
