apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ruoyi
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ruoyi
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        admission.datakit/java-lib.version: ""
    spec:
      containers:
        - name: auth-container
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: JAVA_OPTS
            value: |-
              -javaagent:/datadog-lib/dd-java-agent.jar -Ddd.service=$PREFIX-auth  -Ddd.profiling.enabled=true -Ddd.profiling.allocation.enabled=true -Ddd.tags=container_host:\$(POD_NAME) -Ddd.service.mapping=mysql:$PREFIX-mysql,redis:$PREFIX-redis -Ddd.env=$ENV -Ddd.agent.port=9529
          - name: PARAMS
            value: "--spring.redis.host=\$(REDIS_SERVICE_SERVICE_HOST) --spring.nacos.ip=\$(NACOS_SERVICE_SERVICE_HOST)"
          image: registry.cn-guangzhou.aliyuncs.com/guance-south/ruoyi-auth-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9200
            protocol: TCP
          volumeMounts:
            - name: auth-log
              mountPath: /data/app/logs

      restartPolicy: Always
      volumes:
        - name: auth-log
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      

