apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ruoyi
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ruoyi
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        admission.datakit/java-lib.version: ""
    spec:
      containers:
        - name: auth-container
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: JAVA_OPTS
            value: |-
              -javaagent:/datadog-lib/dd-java-agent.jar -Ddd.service=$PREFIX-auth  -Ddd.profiling.enabled=true  -Ddd.tags=container_host:\$(POD_NAME) -Ddd.service.mapping=mysql:$PREFIX-mysql,redis:$PREFIX-redis -Ddd.env=$ENV -Ddd.agent.port=9529
          - name: PARAMS
            value: "--spring.redis.host=\$(REDIS_SERVICE_SERVICE_HOST) --spring.nacos.ip=\$(NACOS_SERVICE_SERVICE_HOST)"
          image: registry.cn-guangzhou.aliyuncs.com/guance-south/ruoyi-auth-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9200
            protocol: TCP
          volumeMounts:
          - name: varlog
            mountPath: /data/app/logs/ruoyi-auth

        - name: logfwd
          image: pubrepo.jiagouyun.com/datakit/logfwd:1.4.5
          env:
            - name: LOGFWD_DATAKIT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: LOGFWD_DATAKIT_PORT
              value: "9531"
            - name: LOGFWD_ANNOTATION_DATAKIT_LOGS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['datakit/log']
            - name: LOGFWD_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: LOGFWD_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /opt/logfwd/config
              name: logfwd-config
              subPath: config

      restartPolicy: Always
      volumes:
        - name: varlog
          emptyDir: { }
        - configMap:
            name: logfwd-conf
          name: logfwd-config
      

