apiVersion: v1
kind: Service
metadata:
  name: system-service
  namespace: ruoyi
spec:
  selector:
    app: system-pod
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  namespace: ruoyi
  labels:
    app: system-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-pod
  template:
    metadata:
      labels:
        app: system-pod
      annotations:
        admission.datakit/java-lib.version: ""
    spec:
      containers:
      - name: system-container
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: JAVA_OPTS
          value: |-
            -javaagent:/datadog-lib/dd-java-agent.jar -Ddd.service=$PREFIX-system  -Ddd.profiling.enabled=true -Ddd.profiling.allocation.enabled=true -Ddd.tags=container_host:\$(PODE_NAME) -Ddd.service.mapping=mysql:$PREFIX-mysql,redis:$PREFIX-redis -Ddd.env=$ENV -Ddd.agent.port=9529
        - name: PARAMS
          value: "--spring.redis.host=\$(REDIS_SERVICE_SERVICE_HOST) --spring.nacos.ip=\$(NACOS_SERVICE_SERVICE_HOST) --spring.db.ip=\$(MYSQL_SERVICE_SERVICE_HOST)"
        image: registry.cn-guangzhou.aliyuncs.com/guance-south/ruoyi-system-service:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9201
          protocol: TCP
        volumeMounts:
        - name: system-log
          mountPath: /data/app/logs
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi

      restartPolicy: Always
      volumes:
        - name: system-log
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate