apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: ruoyi
  labels:
    app: web-service
spec:
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: ruoyi
  labels:
    app: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - env:
        - name: PODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUM_APPLICATION_ID
          value: "$RUM_APPLICATION_ID"
        - name: ALLOWED_TRACING_ORIGINS
          value: "$ALLOWED_TRACING_ORIGINS"
        - name: PREFIX
          value: "$PREFIX"
        - name: VERSION
          value: "$VERSION"
        - name: ENV
          value: "$ENV"
        name: web-service
        image: registry.cn-guangzhou.aliyuncs.com/guance-south/ruoyi-web-service:v2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP


